var class_custom_editors_1_1_custom_attributes_1_1_sorting_layer_attribute =
[
    [ "SortingLayerDrawer", "class_custom_editors_1_1_custom_attributes_1_1_sorting_layer_attribute_1_1_sorting_layer_drawer.html", "class_custom_editors_1_1_custom_attributes_1_1_sorting_layer_attribute_1_1_sorting_layer_drawer" ]
];